services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '${POSTGRES_PORT}:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: 'redis:latest'
    ports:
      - '6380:6379'

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - 'RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}'
      - 'RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    environment:
      - 'DB_HOST=postgres'
      - 'REDIS_HOST=redis'
      - 'RABBITMQ_HOST=rabbitmq'
      - 'POSTGRES_PORT=5432'
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}'
      - 'RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}'
      - 'JWT_SECRET=${JWT_SECRET}'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
