// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8081' | (string & {});
};

export type WfhRequestDto = {
    id?: string;
    employeeId?: string;
    employeeName?: string;
    startDate?: string;
    endDate?: string;
    status?: 'PENDING' | 'APPROVED' | 'REJECTED';
    reason?: string;
    approvedById?: string;
    approvedByName?: string;
    approvedAt?: string;
    createdAt?: string;
    updatedAt?: string;
};

export type TaskCreateRequest = {
    title: string;
    description?: string;
    assignedToId: string;
    dueDate?: string;
    priority: 'LOW' | 'MEDIUM' | 'HIGH';
};

export type TaskDto = {
    id?: string;
    title?: string;
    description?: string;
    assignedToId?: string;
    assignedToName?: string;
    assignedById?: string;
    assignedByName?: string;
    dueDate?: string;
    status?: 'TODO' | 'IN_PROGRESS' | 'REVIEW' | 'DONE';
    priority?: 'LOW' | 'MEDIUM' | 'HIGH';
    createdAt?: string;
    updatedAt?: string;
};

export type LeaveRequestDto = {
    id?: string;
    employeeId?: string;
    employeeName?: string;
    startDate: string;
    endDate: string;
    leaveType: 'SICK' | 'CASUAL' | 'ANNUAL' | 'UNPAID';
    status?: 'PENDING' | 'APPROVED' | 'REJECTED';
    reason: string;
    approvedById?: string;
    approvedByName?: string;
    approvedAt?: string;
    createdAt?: string;
    updatedAt?: string;
};

export type RegisterRequest = {
    firstName: string;
    lastName: string;
    email: string;
    password: string;
    phone?: string;
    jobTitle?: string;
    departmentCode?: string;
    managerId?: string;
    salary?: number;
    dateOfJoining?: string;
    role?: 'ROLE_ADMIN' | 'ROLE_MANAGER' | 'ROLE_EMPLOYEE';
};

export type EmployeeDto = {
    id?: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    phone?: string;
    jobTitle?: string;
    departmentId?: string;
    departmentCode?: string;
    departmentName?: string;
    salary?: number;
    dateOfJoining?: string;
    status?: 'ACTIVE' | 'INACTIVE' | 'TERMINATED' | 'ON_LEAVE';
    role?: 'ROLE_ADMIN' | 'ROLE_MANAGER' | 'ROLE_EMPLOYEE';
    managerId?: string;
    managerName?: string;
    managerEmail?: string;
    createdAt?: string;
    updatedAt?: string;
};

export type DepartmentDto = {
    id?: string;
    name: string;
    code: string;
    managerId?: string;
    managerName?: string;
    createdAt?: string;
    updatedAt?: string;
};

export type ChangePasswordRequest = {
    currentPassword: string;
    newPassword: string;
};

export type WfhRequestCreate = {
    startDate: string;
    endDate: string;
    reason?: string;
};

export type PerformanceReviewDto = {
    id?: string;
    employeeId: string;
    employeeName?: string;
    reviewerId?: string;
    reviewerName?: string;
    reviewDate?: string;
    feedback: string;
    rating: number;
    createdAt?: string;
    updatedAt?: string;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type LoginResponse = {
    accessToken?: string;
    tokenType?: string;
    email?: string;
    role?: 'ROLE_ADMIN' | 'ROLE_MANAGER' | 'ROLE_EMPLOYEE';
    employeeId?: string;
};

export type AttendanceDto = {
    id?: string;
    employeeId?: string;
    employeeName?: string;
    date?: string;
    clockIn?: string;
    clockOut?: string;
    workLocation?: 'OFFICE' | 'WFH' | 'FIELD';
    workHours?: number;
    createdAt?: string;
    updatedAt?: string;
};

export type NotificationDto = {
    id?: string;
    employeeId?: string;
    employeeName?: string;
    title?: string;
    message?: string;
    type?: 'LEAVE_APPLIED' | 'LEAVE_APPROVED' | 'LEAVE_REJECTED' | 'WFH_APPLIED' | 'WFH_APPROVED' | 'WFH_REJECTED' | 'TASK_ASSIGNED' | 'EMPLOYEE_CREATED';
    createdAt?: string;
    updatedAt?: string;
    read?: boolean;
};

export type RejectWfhData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        reason?: string;
    };
    url: '/api/wfh/{id}/reject';
};

export type RejectWfhResponses = {
    /**
     * OK
     */
    200: WfhRequestDto;
};

export type RejectWfhResponse = RejectWfhResponses[keyof RejectWfhResponses];

export type ApproveWfhData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/wfh/{id}/approve';
};

export type ApproveWfhResponses = {
    /**
     * OK
     */
    200: WfhRequestDto;
};

export type ApproveWfhResponse = ApproveWfhResponses[keyof ApproveWfhResponses];

export type DeleteTaskData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/tasks/{id}';
};

export type DeleteTaskResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetTaskByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/tasks/{id}';
};

export type GetTaskByIdResponses = {
    /**
     * OK
     */
    200: TaskDto;
};

export type GetTaskByIdResponse = GetTaskByIdResponses[keyof GetTaskByIdResponses];

export type UpdateTaskData = {
    body: TaskCreateRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/tasks/{id}';
};

export type UpdateTaskResponses = {
    /**
     * OK
     */
    200: TaskDto;
};

export type UpdateTaskResponse = UpdateTaskResponses[keyof UpdateTaskResponses];

export type UpdateTaskStatusData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        status: 'TODO' | 'IN_PROGRESS' | 'REVIEW' | 'DONE';
    };
    url: '/api/tasks/{id}/status';
};

export type UpdateTaskStatusResponses = {
    /**
     * OK
     */
    200: TaskDto;
};

export type UpdateTaskStatusResponse = UpdateTaskStatusResponses[keyof UpdateTaskStatusResponses];

export type MarkAsReadData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/notifications/{id}/read';
};

export type MarkAsReadResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MarkAllAsReadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/notifications/read-all';
};

export type MarkAllAsReadResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RejectLeaveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        reason?: string;
    };
    url: '/api/leaves/{id}/reject';
};

export type RejectLeaveResponses = {
    /**
     * OK
     */
    200: LeaveRequestDto;
};

export type RejectLeaveResponse = RejectLeaveResponses[keyof RejectLeaveResponses];

export type ApproveLeaveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/leaves/{id}/approve';
};

export type ApproveLeaveResponses = {
    /**
     * OK
     */
    200: LeaveRequestDto;
};

export type ApproveLeaveResponse = ApproveLeaveResponses[keyof ApproveLeaveResponses];

export type DeleteEmployeeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/employees/{id}';
};

export type DeleteEmployeeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetEmployeeByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/employees/{id}';
};

export type GetEmployeeByIdResponses = {
    /**
     * OK
     */
    200: EmployeeDto;
};

export type GetEmployeeByIdResponse = GetEmployeeByIdResponses[keyof GetEmployeeByIdResponses];

export type UpdateEmployeeData = {
    body: RegisterRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/employees/{id}';
};

export type UpdateEmployeeResponses = {
    /**
     * OK
     */
    200: EmployeeDto;
};

export type UpdateEmployeeResponse = UpdateEmployeeResponses[keyof UpdateEmployeeResponses];

export type DeleteDepartmentData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/departments/{id}';
};

export type DeleteDepartmentResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetDepartmentByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/departments/{id}';
};

export type GetDepartmentByIdResponses = {
    /**
     * OK
     */
    200: DepartmentDto;
};

export type GetDepartmentByIdResponse = GetDepartmentByIdResponses[keyof GetDepartmentByIdResponses];

export type UpdateDepartmentData = {
    body: DepartmentDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/departments/{id}';
};

export type UpdateDepartmentResponses = {
    /**
     * OK
     */
    200: DepartmentDto;
};

export type UpdateDepartmentResponse = UpdateDepartmentResponses[keyof UpdateDepartmentResponses];

export type ChangePasswordData = {
    body: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/auth/change-password';
};

export type ChangePasswordResponses = {
    /**
     * OK
     */
    200: string;
};

export type ChangePasswordResponse = ChangePasswordResponses[keyof ChangePasswordResponses];

export type GetAllWfhRequestsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/wfh';
};

export type GetAllWfhRequestsResponses = {
    /**
     * OK
     */
    200: Array<WfhRequestDto>;
};

export type GetAllWfhRequestsResponse = GetAllWfhRequestsResponses[keyof GetAllWfhRequestsResponses];

export type ApplyForWfhData = {
    body: WfhRequestCreate;
    path?: never;
    query?: never;
    url: '/api/wfh';
};

export type ApplyForWfhResponses = {
    /**
     * OK
     */
    200: WfhRequestDto;
};

export type ApplyForWfhResponse = ApplyForWfhResponses[keyof ApplyForWfhResponses];

export type CreateTaskData = {
    body: TaskCreateRequest;
    path?: never;
    query?: never;
    url: '/api/tasks';
};

export type CreateTaskResponses = {
    /**
     * OK
     */
    200: TaskDto;
};

export type CreateTaskResponse = CreateTaskResponses[keyof CreateTaskResponses];

export type CreateReviewData = {
    body: PerformanceReviewDto;
    path?: never;
    query?: never;
    url: '/api/reviews';
};

export type CreateReviewResponses = {
    /**
     * OK
     */
    200: PerformanceReviewDto;
};

export type CreateReviewResponse = CreateReviewResponses[keyof CreateReviewResponses];

export type GetAllLeaveRequestsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/leaves';
};

export type GetAllLeaveRequestsResponses = {
    /**
     * OK
     */
    200: Array<LeaveRequestDto>;
};

export type GetAllLeaveRequestsResponse = GetAllLeaveRequestsResponses[keyof GetAllLeaveRequestsResponses];

export type ApplyForLeaveData = {
    body: LeaveRequestDto;
    path?: never;
    query?: never;
    url: '/api/leaves';
};

export type ApplyForLeaveResponses = {
    /**
     * OK
     */
    200: LeaveRequestDto;
};

export type ApplyForLeaveResponse = ApplyForLeaveResponses[keyof ApplyForLeaveResponses];

export type GetAllDepartmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/departments';
};

export type GetAllDepartmentsResponses = {
    /**
     * OK
     */
    200: Array<DepartmentDto>;
};

export type GetAllDepartmentsResponse = GetAllDepartmentsResponses[keyof GetAllDepartmentsResponses];

export type CreateDepartmentData = {
    body: DepartmentDto;
    path?: never;
    query?: never;
    url: '/api/departments';
};

export type CreateDepartmentResponses = {
    /**
     * OK
     */
    200: DepartmentDto;
};

export type CreateDepartmentResponse = CreateDepartmentResponses[keyof CreateDepartmentResponses];

export type RegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterResponses = {
    /**
     * OK
     */
    200: EmployeeDto;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type RefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/refresh';
};

export type RefreshResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutResponses = {
    /**
     * OK
     */
    200: string;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];

export type PunchOutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/attendance/punch-out';
};

export type PunchOutResponses = {
    /**
     * OK
     */
    200: AttendanceDto;
};

export type PunchOutResponse = PunchOutResponses[keyof PunchOutResponses];

export type PunchInData = {
    body?: never;
    path?: never;
    query?: {
        location?: 'OFFICE' | 'WFH' | 'FIELD';
    };
    url: '/api/attendance/punch-in';
};

export type PunchInResponses = {
    /**
     * OK
     */
    200: AttendanceDto;
};

export type PunchInResponse = PunchInResponses[keyof PunchInResponses];

export type GetPendingRequestsForManagerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/wfh/pending';
};

export type GetPendingRequestsForManagerResponses = {
    /**
     * OK
     */
    200: Array<WfhRequestDto>;
};

export type GetPendingRequestsForManagerResponse = GetPendingRequestsForManagerResponses[keyof GetPendingRequestsForManagerResponses];

export type GetMyWfhRequestsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/wfh/my';
};

export type GetMyWfhRequestsResponses = {
    /**
     * OK
     */
    200: Array<WfhRequestDto>;
};

export type GetMyWfhRequestsResponse = GetMyWfhRequestsResponses[keyof GetMyWfhRequestsResponses];

export type GetWfhRequestsByEmployeeData = {
    body?: never;
    path: {
        employeeId: string;
    };
    query?: never;
    url: '/api/wfh/employee/{employeeId}';
};

export type GetWfhRequestsByEmployeeResponses = {
    /**
     * OK
     */
    200: Array<WfhRequestDto>;
};

export type GetWfhRequestsByEmployeeResponse = GetWfhRequestsByEmployeeResponses[keyof GetWfhRequestsByEmployeeResponses];

export type GetMyTasksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tasks/my';
};

export type GetMyTasksResponses = {
    /**
     * OK
     */
    200: Array<TaskDto>;
};

export type GetMyTasksResponse = GetMyTasksResponses[keyof GetMyTasksResponses];

export type GetTasksCreatedByData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tasks/created';
};

export type GetTasksCreatedByResponses = {
    /**
     * OK
     */
    200: Array<TaskDto>;
};

export type GetTasksCreatedByResponse = GetTasksCreatedByResponses[keyof GetTasksCreatedByResponses];

export type GetEmployeeReviewsData = {
    body?: never;
    path: {
        employeeId: string;
    };
    query?: never;
    url: '/api/reviews/employee/{employeeId}';
};

export type GetEmployeeReviewsResponses = {
    /**
     * OK
     */
    200: Array<PerformanceReviewDto>;
};

export type GetEmployeeReviewsResponse = GetEmployeeReviewsResponses[keyof GetEmployeeReviewsResponses];

export type GetMyNotificationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/notifications';
};

export type GetMyNotificationsResponses = {
    /**
     * OK
     */
    200: Array<NotificationDto>;
};

export type GetMyNotificationsResponse = GetMyNotificationsResponses[keyof GetMyNotificationsResponses];

export type GetMyUnreadCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/notifications/unread/count';
};

export type GetMyUnreadCountResponses = {
    /**
     * OK
     */
    200: number;
};

export type GetMyUnreadCountResponse = GetMyUnreadCountResponses[keyof GetMyUnreadCountResponses];

export type GetPendingRequestsForManager1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/leaves/pending';
};

export type GetPendingRequestsForManager1Responses = {
    /**
     * OK
     */
    200: Array<LeaveRequestDto>;
};

export type GetPendingRequestsForManager1Response = GetPendingRequestsForManager1Responses[keyof GetPendingRequestsForManager1Responses];

export type GetMyLeaveRequestsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/leaves/my';
};

export type GetMyLeaveRequestsResponses = {
    /**
     * OK
     */
    200: Array<LeaveRequestDto>;
};

export type GetMyLeaveRequestsResponse = GetMyLeaveRequestsResponses[keyof GetMyLeaveRequestsResponses];

export type GetLeaveRequestsByEmployeeData = {
    body?: never;
    path: {
        employeeId: string;
    };
    query?: never;
    url: '/api/leaves/employee/{employeeId}';
};

export type GetLeaveRequestsByEmployeeResponses = {
    /**
     * OK
     */
    200: Array<LeaveRequestDto>;
};

export type GetLeaveRequestsByEmployeeResponse = GetLeaveRequestsByEmployeeResponses[keyof GetLeaveRequestsByEmployeeResponses];

export type GetAllEmployeesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/employees';
};

export type GetAllEmployeesResponses = {
    /**
     * OK
     */
    200: Array<EmployeeDto>;
};

export type GetAllEmployeesResponse = GetAllEmployeesResponses[keyof GetAllEmployeesResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type GetMeResponses = {
    /**
     * OK
     */
    200: EmployeeDto;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type GetPunchStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/attendance/status';
};

export type GetPunchStatusResponses = {
    /**
     * OK
     */
    200: AttendanceDto;
};

export type GetPunchStatusResponse = GetPunchStatusResponses[keyof GetPunchStatusResponses];

export type GetMyAttendanceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/attendance/my';
};

export type GetMyAttendanceResponses = {
    /**
     * OK
     */
    200: Array<AttendanceDto>;
};

export type GetMyAttendanceResponse = GetMyAttendanceResponses[keyof GetMyAttendanceResponses];

export type GetTotalHoursData = {
    body?: never;
    path?: never;
    query: {
        employeeId: string;
        startDate: string;
        endDate: string;
    };
    url: '/api/attendance/hours';
};

export type GetTotalHoursResponses = {
    /**
     * OK
     */
    200: number;
};

export type GetTotalHoursResponse = GetTotalHoursResponses[keyof GetTotalHoursResponses];

export type GetEmployeeAttendanceData = {
    body?: never;
    path: {
        employeeId: string;
    };
    query?: {
        startDate?: string;
        endDate?: string;
    };
    url: '/api/attendance/employee/{employeeId}';
};

export type GetEmployeeAttendanceResponses = {
    /**
     * OK
     */
    200: Array<AttendanceDto>;
};

export type GetEmployeeAttendanceResponse = GetEmployeeAttendanceResponses[keyof GetEmployeeAttendanceResponses];

export type GetAllAttendanceByDateData = {
    body?: never;
    path: {
        date: string;
    };
    query?: never;
    url: '/api/attendance/date/{date}';
};

export type GetAllAttendanceByDateResponses = {
    /**
     * OK
     */
    200: Array<AttendanceDto>;
};

export type GetAllAttendanceByDateResponse = GetAllAttendanceByDateResponses[keyof GetAllAttendanceByDateResponses];
