spring.application.name=backend

# Datasource and JPA Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Database Initialization
spring.sql.init.mode=always

# Redis Configuration (Spring Boot Docker Compose will override at runtime)
spring.data.redis.host=localhost
spring.data.redis.port=6380

# JWT Token Configuration
# Strong 512-bit base64/hex key for HMAC-SHA512
ems.jwt.secret=9a67a361c472304918e7e174b5952d43a5023961ef024e0b02130e5881cc1498b31a31d9a0d810842db237f3a8b27c1d76326127b38b693240e8e453086a9f47
ems.jwt.accessTokenExpirationMs=900000
ems.jwt.refreshTokenExpirationMs=604800000

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=emsuser
spring.rabbitmq.password=emspass

# Mail Configuration
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
