spring.application.name=backend
server.port=8081

# Datasource and JPA Configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:emsdb}?options=-c%20timezone=UTC
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:salman}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Database Initialization
spring.sql.init.mode=always

# Redis Configuration (Spring Boot Docker Compose will override at runtime)
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=6380

# JWT Token Configuration
# Strong 512-bit base64/hex key for HMAC-SHA512
ems.jwt.secret=${JWT_SECRET:9a67a361c472304918e7e174b5952d43a5023961ef024e0b02130e5881cc1498b31a31d9a0d810842db237f3a8b27c1d76326127b38b693240e8e453086a9f47}
ems.jwt.accessTokenExpirationMs=900000
ems.jwt.refreshTokenExpirationMs=604800000

# RabbitMQ Configuration
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_DEFAULT_USER:emsuser}
spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS:emspass}

# Mail Configuration
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# Client Application URL
ems.frontend.url=${FRONTEND_URL:http://localhost:3000}

